name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: | 
        g++ -O0 -g -W -Wall -pedantic -std=c++11 main.cpp 
    - name: make
      run: |
        ./a.out
        
        
